shared:
  main:
    - name: preview
      partial: lookbook/previews/panels/preview
      label: Preview
      hotkey: v

    - name: output
      partial: lookbook/previews/panels/output
      label: HTML
      hotkey: h

  drawer:
    - name: source
      partial: lookbook/previews/panels/source
      label: Source
      hotkey: s
      copy: "->(data) { data.examples.map { |e| e.source }.join(\n) }"

    - name: notes
      partial: lookbook/previews/panels/notes
      label: Notes
      hotkey: n
      disabled: ->(data) { data.examples.select { |e| e.notes.present? }.none? }

    - name: params
      partial: lookbook/previews/panels/params
      label: Params
      hotkey: p
      disabled: ->(data) { data.preview.params.none? }
